# Generated by Django 3.2.4 on 2024-04-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('mainImage', models.CharField(max_length=5000)),
                ('isPrivate', models.BooleanField()),
            ],
        ),
    ]
