# Generated by Django 3.2.4 on 2024-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='mainImage',
            field=models.CharField(max_length=50000),
        ),
    ]
