# Generated by Django 3.2.4 on 2024-11-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0002_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='criteria',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.CharField(max_length=5000000, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=50),
        ),
    ]
