# Generated by Django 3.2.4 on 2024-04-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_session'),
        ('communityAPI', '0003_alter_community_mainimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityUserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('owner', 'Owner')], max_length=50)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityAPI.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAPI.user')),
            ],
        ),
    ]
