# Generated by Django 3.2.4 on 2024-11-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0003_auto_20241111_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
    ]
