# Generated by Django 3.2.4 on 2024-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0004_communityuserconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityuserconnection',
            name='type',
            field=models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('owner', 'Owner'), ('banned', 'Banned')], max_length=50),
        ),
    ]
