# Generated by Django 3.2.4 on 2024-11-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0005_alter_userbadge_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.CharField(max_length=5000000, null=True),
        ),
    ]
