# Generated by Django 3.2.4 on 2024-11-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0002_post_tags'),
        ('communityAPI', '0006_badge_image'),
    ]

    operations = [
    ]
