# Generated by Django 3.2.4 on 2024-04-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_session'),
        ('communityAPI', '0007_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowValues', models.JSONField(default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('upvoteCount', models.IntegerField(default=0)),
                ('downvoteCount', models.IntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityAPI.community')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAPI.user')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityAPI.template')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('upvoteCount', models.IntegerField(default=0)),
                ('downvoteCount', models.IntegerField(default=0)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAPI.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityAPI.post')),
            ],
        ),
    ]
