# Generated by Django 3.2.4 on 2024-12-08 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communityAPI', '0008_communitytagusage_userrecommendation_usertagusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_post', 'Created a post'), ('add_comment', 'Added a comment'), ('create_template', 'Created a template'), ('earn_badge', 'Earned a badge'), ('like_post', 'Liked a post'), ('like_comment', 'Liked a comment'), ('follow_user', 'Followed a user'), ('join_community', 'Joined a community')], max_length=50)),
                ('target', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communityAPI.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
