# Generated by Django 3.2.4 on 2024-12-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('communityAPI', '0008_communitytagusage_userrecommendation_usertagusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSemanticMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.CharField(blank=True, max_length=50, null=True)),
                ('semantic_data', models.JSONField(blank=True, null=True)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_metadata', to='taggit.tag')),
            ],
        ),
    ]
