# Generated by Django 3.2.4 on 2024-04-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0008_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvoteCount',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvoteCount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvoteCount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvoteCount',
        ),
    ]
