# Generated by Django 3.2.4 on 2024-04-22 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_session'),
        ('communityAPI', '0009_auto_20240421_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('direction', models.BooleanField()),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAPI.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityAPI.post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('direction', models.BooleanField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityAPI.comment')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAPI.user')),
            ],
        ),
    ]
