# Generated by Django 3.2.4 on 2024-12-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('communityAPI', '0009_communityactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactivity',
            name='action',
            field=models.CharField(choices=[('create_post', 'Created a post'), ('add_comment', 'Added a comment'), ('create_template', 'Created a template'), ('earn_badge', 'Earned a badge'), ('like_post', 'Liked a post'), ('like_comment', 'Liked a comment'), ('follow_user', 'Followed a user'), ('join_community', 'Joined a community'), ('create_community', 'Created a community'), ('create_badge', 'Created a badge'), ('make_moderator', 'Assign a moderator'), ('ban_user', 'Banned a user'), ('make_owner', 'Assign an owner')], max_length=50),
        ),
        migrations.CreateModel(
            name='TagSemanticMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=50, null=True)),
                ('semantic_data', models.JSONField(blank=True, null=True)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_metadata', to='taggit.tag')),
            ],
        ),
    ]
