# Generated by Django 3.2.4 on 2024-12-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0009_communityactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactivity',
            name='action',
            field=models.CharField(choices=[('create_post', 'Created a post'), ('add_comment', 'Added a comment'), ('create_template', 'Created a template'), ('earn_badge', 'Earned a badge'), ('like_post', 'Liked a post'), ('like_comment', 'Liked a comment'), ('follow_user', 'Followed a user'), ('join_community', 'Joined a community'), ('create_community', 'Created a community'), ('create_badge', 'Created a badge'), ('make_moderator', 'Assign a moderator'), ('ban_user', 'Banned a user'), ('make_owner', 'Assign an owner')], max_length=50),
        ),
    ]
