# Generated by Django 3.2.4 on 2024-12-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0009_tagsemanticmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsemanticmetadata',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
