# Generated by Django 3.2.4 on 2024-04-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0012_alter_community_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
    ]
