# Generated by Django 3.2.4 on 2024-05-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0014_userfollowconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
    ]
