# Generated by Django 3.2.4 on 2024-05-16 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0015_auto_20240514_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
