# Generated by Django 3.2.4 on 2024-05-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityAPI', '0016_community_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
