from django.urls import path
from communityAPI import views

urlpatterns = [
	path('create-community/', views.CreateCommunity.as_view(), name='create_community'),
	path('get-community-info', views.get_community_info, name='get_community_info'),
	path('get-user-communities', views.get_user_communities, name='get_user_communities'),
    path('get-communities', views.get_communities, name='get_communities'),
	path('join-community', views.join_community, name='join_community'),
	path('leave-community', views.leave_community, name='leave_community'),
	path('create-invitation', views.create_invitation, name='create_invitation'),
    path('cancel-invitation', views.cancel_invitation, name='cancel_invitation'),
	path('get-community-members', views.get_community_members, name='get_community_members'),
	path('get-community-banned', views.get_community_banned, name='get_community_banned'),
	path('get-community-moderators', views.get_community_moderators, name='get_community_moderators'),
	path('get-community-owners', views.get_community_owners, name='get_community_owners'),
	path('assign-moderator', views.assign_moderator, name='assign_moderator'),
    path('change-ownership', views.change_ownership, name='change_ownership'),
	path('get-invitations-community', views.get_invitations_by_community, name='get_invitations_by_community'),
	path('get-invitations-user', views.get_invitations_by_user, name='get_invitations_by_user'),
	path('response-invitation', views.response_invitation, name='response_invitation'),
	path('get-community-posts', views.get_community_posts, name='get_community_posts'),
    path('get-user-feed', views.get_user_feed, name='get_user_feed'),
	path('templates/create-template', views.create_template, name='create_template'),
	path('templates/get-templates', views.get_templates, name='get_templates'),
	path('templates/get-template', views.get_template, name='get_template'),
    path('templates/delete-template', views.delete_template, name='delete_template'),
	path('create-post', views.create_post, name='create_post'),
	path('add-comment', views.add_comment, name='add_comment'),
	path('get-post-comments', views.get_post_comments, name='get_post_comments'),
	path('like-post', views.like_post, name='like_post'),
	path('like-comment', views.like_comment, name='like_comment'),
	path('follow-user', views.follow_user, name='follow_user'),
	path('get-user-connections', views.get_user_connections, name='get_user_connections'),
	path('ban-user', views.ban_user, name='ban_user'),
	path('delete-post', views.delete_post, name='delete_post'),
	path('delete-comment', views.delete_comment, name='delete_comment'),
	path('get-post-details', views.get_post_details, name='get_post_details'),
	path('edit-post', views.edit_post, name='edit_post'),
	path('edit-comment', views.edit_comment, name='edit_comment'),
    path('get-top-communities', views.get_top_communities, name='get_top_communities'),
    path('get-owned-communities', views.get_owned_communities, name='get_owned_communities'),
    path('archive-community', views.archive_community, name='archive_community'),
    path('get-main-search', views.get_main_search, name='get_main_search'),
]