name: Deploy to Server

on:
  push:
    branches:
      - main
      - dev
      - feature/cd-pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEV_PATH: /var/www/huddleup-dev/huddleup
          MAIN_PATH: /var/www/huddleup
          BRANCH_NAME: feature/cd-pipeline # ${{ github.ref_name }}
        run: |
          # Determine deployment path based on branch
          if [ "$BRANCH_NAME" = "dev" ]; then
            DEPLOY_PATH=$DEV_PATH
          elif [ "$BRANCH_NAME" = "main" ]; then
            DEPLOY_PATH=$MAIN_PATH
          elif [ "$BRANCH_NAME" = "feature/cd-pipeline" ]; then
            DEPLOY_PATH=$DEV_PATH
          else
            echo "Branch not recognized, exiting."
            exit 1
          fi

          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST << EOF
            set -e  # Ensure script stops on error

            echo "Branch: $BRANCH_NAME"
            echo "Deploy path: $DEPLOY_PATH"


            cd $DEPLOY_PATH

            # Stop existing containers
            docker-compose -f docker-compose.yaml -p $BRANCH_NAME down || echo "No containers to stop."

            # Discard local changes
            git reset --hard

            # Pull latest changes
            git pull origin $BRANCH_NAME

            # Modify docker-compose.yaml for dev branch
            if [ "$BRANCH_NAME" = "dev" ]; then
              sed -i 's/127.0.0.1:8080:80/127.0.0.1:8081:80/' docker-compose.yaml
            elif [ "$BRANCH_NAME" = "feature/cd-pipeline" ]; then
              sed -i 's/127.0.0.1:8080:80/127.0.0.1:8081:80/' docker-compose.yaml
            fi

            # Build and start containers
            docker-compose -f docker-compose.yaml -p $BRANCH_NAME up --build -d
          EOF