name: Deploy to Server

on:
  push:
    branches:
      # - main
      - dev
      - feature/cd-pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Modify frontend ports in docker-compose.yml for dev branch
        if: github.ref_name == 'feature/cd-pipeline'
        run: |
          sed -i 's/127.0.0.1:8080:80/127.0.0.1:8081:80/' docker-compose.yaml

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEV_PATH: /var/www/huddleup-dev/huddleup
          MAIN_PATH: /var/www/huddleup
          BRANCH_NAME: dev # ${{ github.ref_name }}
        run: |
          # Determine deployment path based on branch
          if [ "$BRANCH_NAME" == "dev" ]; then
            DEPLOY_PATH=$DEV_PATH
          elif [ "$BRANCH_NAME" == "main" ]; then
            DEPLOY_PATH=$MAIN_PATH
          else
            echo "Branch not recognized, exiting."
            exit 1
          fi

          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "
            cd $PROJECT_PATH &&
            docker-compose -f docker-compose.yaml -p $BRANCH_NAME down &&
            git pull origin $BRANCH_NAME &&
            if [ "$BRANCH_NAME" == "dev" ]; then \
              sed -i 's/127.0.0.1:8080:80/127.0.0.1:8081:80/' docker-compose.yaml \
            fi &&
            docker-compose -f docker-compose.yaml -p $BRANCH_NAME up --build -d
          "