name: CI Test

on:
  pull_request:
    branches: [ "dev" ]
  merge_group:
    types: [checks_requested]

jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Load .env file
      uses: xom9ikk/dotenv@v2.3.0
      with:
        mode: sample

    - name: Install dependencies
      run: pip install -r ./huddleupAPI/requirements.txt

    - name: Run tests
      run: |
        cd huddleupAPI
        python manage.py test